### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by boxed**
- Cleaned up the code
- Added automatic download of needed file
- Fixed requirements
- Improved README

The example still doesn't work for me though. The mouse cursor is moved in big chunks seemingly at random directions, and it prints "wink wink" also seemingly at random.

You should also fix the comments that are not in English to be in English.

### CODE REVIEW

**Comment by rfontalva** [comment]
Thanks for your changes and taking time to review my code! I really
appreciate it.
Regarding the performance of the example, it is vastly associated with the
quality of your webcam, the lighting and the speed at which your computer
refreshes.
You can try:
Shining a light at your face.
Decreasing the variable called CoefSens.

Thank you!

**Comment by boxed** [comment]
What is it supposed to do? Move the cursor to where I'm looking or move it if I look at a certain direction?

**Comment by rfontalva** [comment]
It should move as your head moves, if you tilt a little to the right it
will move little by little to the right, if you tilt a lot to the left it
will move faster in that direction and so on.

**Comment by boxed** [comment]
Aha! Well that works actually quite well when you know what it's supposed to do! You should write this in the documentation. 

It should have some minimum threshold though. I can't get the cursor to stay still.

If you like these changes, please press the merge button.

**Comment by rfontalva** [comment]
I haven't been able to check them yet, but I sure will! Thank you again for
your interest and suggestions

**Review by rfontalva — APPROVED** [review]

**Pull request merged**
